### ISSUE TITLE
Update block-size argument from ANY to 32K.

### ISSUE THREAD

**Issue by vaughandelport** [NetAppDocs/keystone-staas#10]
Page: [Quality of Service (QoS) in Keystone](https://docs.netapp.com/us-en/keystone-staas/concepts/qos.html)

Please change the argument "-block-size Any" to "-block-size 32K" in all five of the 'Sample command' sections.

**Comment by vaughandelport** [comment]
To provide an example, our sample command for the Value service level is:
`qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 59`

This should instead be:
`qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 59`

(Note the change to the -block-size)

**Comment by netapp-manini** [comment]
@vaughandelport thanks for your comment. We will look into this issue and update you when published.

**Comment by vaughandelport** [comment]
@netapp-manini can we please include the following changes in addition to the above?

Standard aQoS example:

OLD:
`qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 77`

NEW:
`qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 75`

Value aQoS example:

OLD:
`qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 59`

NEW:
`qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any -absolute-min-iops 75`

**Comment by netapp-manini** [comment]
@vaughandelport do I take the last examples for only standard and Value, and keep the block-size for the remaining as 32K, or change all to "Any"?

**Comment by vaughandelport** [comment]
@netapp-manini The changes above to `-absolute-min-iops`. Please see https://github.com/NetAppDocs/keystone-staas/pull/11/files for a consolidated list of changes.

**Comment by netapp-manini** [comment]
Thanks, @vaughandelport I will take a look and do the needful.

**Comment by netapp-manini** [comment]
All comments, including the discrete ones in the PR have been fixed at:

https://docs.netapp.com/us-en/keystone-staas/concepts/qos.html#configuration-of-adaptive-qos-policy-group
