### ISSUE TITLE
Feedback on 'Virtual infrastructure requirements'

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/keystone-staas#32]
### Summary

https://docs.netapp.com/us-en/keystone-staas/installation/vapp-prereqs.html#networking-requirements
The 2 following HTTPS “centos.org” URL’s on this page do not work:
 
[https://mirror.centos.org](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmirror.centos.org%2F&data=05%7C02%7CChanda.Jha%40netapp.com%7Ca3a227d928184b9b140308dbfbe648a6%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638380738696826542%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=suvTiF495SneWjJPfLu78l%2BOABPa4mQZyekbzxPKO2g%3D&reserved=0)
[https://mirrorlist.centos.org](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmirrorlist.centos.org%2F&data=05%7C02%7CChanda.Jha%40netapp.com%7Ca3a227d928184b9b140308dbfbe648a6%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638380738696982821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SyyTw9SToiimVPdd1IyqNAzfcKdKSPAJJbd%2BieqPNok%3D&reserved=0)
 
Can you please updated them to the correct working HTTP URL’s below:
 
[http://mirror.centos.org](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fmirror.centos.org%2F&data=05%7C02%7CChanda.Jha%40netapp.com%7Ca3a227d928184b9b140308dbfbe648a6%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638380738696982821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FFrzdGTtzs8OX965C2dBxpgreKjeNquZtXQiCNX7mwI%3D&reserved=0)
[http://mirrorlist.centos.org](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fmirrorlist.centos.org%2F&data=05%7C02%7CChanda.Jha%40netapp.com%7Ca3a227d928184b9b140308dbfbe648a6%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638380738696982821%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x7AUq4xryJbXQAQ%2FCB2FirduDpVjTxrqhYVe7tRNwrQ%3D&reserved=0)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
This is already in discussion. Will fix it in the next release and update the issue.

**Comment by netapp-manini** [comment]
Fixed: https://docs.netapp.com/us-en/keystone-staas/installation/vapp-prereqs.html#url-access
