### ISSUE TITLE
AQoS instead of QoS

### ISSUE THREAD

**Issue by mattd05** [NetAppDocs/keystone-staas#55]
### Page URL

https://docs.netapp.com/us-en/keystone-staas/concepts/misc-volume-billing.html

### Page title

Miscellaneous scenarios for Keystone billing

### Summary

Adaptive QoS (AQoS) and fixed QoS (QoS) are two different policy on the OnTap system.  
They should not be used interchangeably, which is what I can see in:
- Billing and adaptive QoS policies
- Billing for SnapMirror destinations
- Billing for LUNs
In these three headings the descriptions are referring to QoS, when it should be AQoS.
Fixed QoS (QoS) is unsupported in Keystone StaaS.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-shwetav** [comment]
Hi @mattd05,

Thank you for pointing this out. We will look into it and figure out the best way to address it.
Your help in improving our documentation is much appreciated.

Regards,
Shweta

**Comment by netapp-shwetav** [comment]
Hi @mattd05:
Thank you for your patience.
We have made the changes. 
Link: https://docs.netapp.com/us-en/keystone-staas/concepts/misc-volume-billing.html
Let me know if you have more doubts.
