### ISSUE TITLE
Change of Keystone STaaS QoS Definition to match program updates

### ISSUE THREAD

**Issue by kpapreck** [NetAppDocs/keystone-staas#6]
Page: [Quality of Service (QoS) in Keystone](https://docs.netapp.com/us-en/keystone-staas/concepts/qos.html)

Requested changes to the Settings of adaptive QoS Policies documentation to match Keystone program:

Settings for Extreme service level
qos adaptive-policy-group create -policy group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any –absolute-min-iops 1000

Settings for Premium service level
qos adaptive-policy-group create -policy group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any –absolute-min-iops 500

Settings for Performance service level
qos adaptive-policy-group create -policy group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any –absolute-min-iops 250 

NEW SECTION TO ADD BEFORE VALUE
Settings for Standard service level
Settings and commands for the Standard service level:

Sample command:
qos adaptive-policy-group create -policy group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any –absolute-min-iops 77

Sample command:
Settings for Value service level
qos adaptive-policy-group create -policy group <Keystone_standard> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size Any –absolute-min-iops 59

**Comment by netapp-manini** [comment]
@kpapreck thanks for getting back to us. We will check this information, do the needful, and update this thread. In case I need more information, will contact you.

**Comment by netapp-manini** [comment]
@kpapreck 
 
This issue has been addressed at https://docs.netapp.com/us-en/keystone-staas/concepts/qos.html.

Closing this issue.
